CREATE SEQUENCE IF NOT EXISTS auto_seq START WITH 1 INCREMENT BY 50;

ALTER TABLE ONLY auto
    ADD CONSTRAINT autos_param_pkey PRIMARY KEY (id);

ALTER TABLE auto
    ALTER COLUMN fuel DROP NOT NULL;

ALTER TABLE auto
    ALTER COLUMN name DROP NOT NULL;